import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import "@/app/global.scss";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="container">
          <Header />
          <div className="row" style={{ height: "85vh" }}>
            {children}
          </div>
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
